// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: minify.proto
#ifndef GRPC_minify_2eproto__INCLUDED
#define GRPC_minify_2eproto__INCLUDED

#include "minify.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace minify {

// The greeting service definition.
class Minifier final {
 public:
  static constexpr char const* service_full_name() {
    return "minify.Minifier";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends a greeting
    virtual ::grpc::Status Minify(::grpc::ClientContext* context, const ::minify::MinifyRequest& request, ::minify::MinifyReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::minify::MinifyReply>> AsyncMinify(::grpc::ClientContext* context, const ::minify::MinifyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::minify::MinifyReply>>(AsyncMinifyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::minify::MinifyReply>> PrepareAsyncMinify(::grpc::ClientContext* context, const ::minify::MinifyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::minify::MinifyReply>>(PrepareAsyncMinifyRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Sends a greeting
      virtual void Minify(::grpc::ClientContext* context, const ::minify::MinifyRequest* request, ::minify::MinifyReply* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::minify::MinifyReply>* AsyncMinifyRaw(::grpc::ClientContext* context, const ::minify::MinifyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::minify::MinifyReply>* PrepareAsyncMinifyRaw(::grpc::ClientContext* context, const ::minify::MinifyRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Minify(::grpc::ClientContext* context, const ::minify::MinifyRequest& request, ::minify::MinifyReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::minify::MinifyReply>> AsyncMinify(::grpc::ClientContext* context, const ::minify::MinifyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::minify::MinifyReply>>(AsyncMinifyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::minify::MinifyReply>> PrepareAsyncMinify(::grpc::ClientContext* context, const ::minify::MinifyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::minify::MinifyReply>>(PrepareAsyncMinifyRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Minify(::grpc::ClientContext* context, const ::minify::MinifyRequest* request, ::minify::MinifyReply* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::minify::MinifyReply>* AsyncMinifyRaw(::grpc::ClientContext* context, const ::minify::MinifyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::minify::MinifyReply>* PrepareAsyncMinifyRaw(::grpc::ClientContext* context, const ::minify::MinifyRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Minify_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends a greeting
    virtual ::grpc::Status Minify(::grpc::ServerContext* context, const ::minify::MinifyRequest* request, ::minify::MinifyReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Minify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Minify() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Minify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Minify(::grpc::ServerContext* context, const ::minify::MinifyRequest* request, ::minify::MinifyReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMinify(::grpc::ServerContext* context, ::minify::MinifyRequest* request, ::grpc::ServerAsyncResponseWriter< ::minify::MinifyReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Minify<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Minify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_Minify() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ExperimentalWithCallbackMethod_Minify<BaseClass>, ::minify::MinifyRequest, ::minify::MinifyReply>(
          [this](::grpc::ServerContext* context,
                 const ::minify::MinifyRequest* request,
                 ::minify::MinifyReply* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->Minify(context, request, response, controller);
                 }, this));
    }
    ~ExperimentalWithCallbackMethod_Minify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Minify(::grpc::ServerContext* context, const ::minify::MinifyRequest* request, ::minify::MinifyReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void Minify(::grpc::ServerContext* context, const ::minify::MinifyRequest* request, ::minify::MinifyReply* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_Minify<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Minify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Minify() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Minify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Minify(::grpc::ServerContext* context, const ::minify::MinifyRequest* request, ::minify::MinifyReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Minify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_Minify() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Minify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Minify(::grpc::ServerContext* context, const ::minify::MinifyRequest* request, ::minify::MinifyReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMinify(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Minify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_Minify() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ExperimentalWithRawCallbackMethod_Minify<BaseClass>, ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->Minify(context, request, response, controller);
                 }, this));
    }
    ~ExperimentalWithRawCallbackMethod_Minify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Minify(::grpc::ServerContext* context, const ::minify::MinifyRequest* request, ::minify::MinifyReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void Minify(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Minify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Minify() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::minify::MinifyRequest, ::minify::MinifyReply>(std::bind(&WithStreamedUnaryMethod_Minify<BaseClass>::StreamedMinify, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Minify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Minify(::grpc::ServerContext* context, const ::minify::MinifyRequest* request, ::minify::MinifyReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedMinify(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::minify::MinifyRequest,::minify::MinifyReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Minify<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Minify<Service > StreamedService;
};

}  // namespace minify


#endif  // GRPC_minify_2eproto__INCLUDED
